# Configuration all env mail
SMTP_ADDRESS: 'mail.loginhost.com.br'
SMTP_PORT: '587'
SMTP_DOMAIN: 'loginhost.com.br'
SMTP_USER_NAME: 'sendmail@loginhost.com.br'
SMTP_PASSWORD: 'W3Case6385#@'

# From email
SMTP_FROM_MAIL: 'atendimento@agenciaw3.digital'

# Paths and URls
UPLOAD_HOST: 'http://cdn1.localtest.me:3000/'
SFTP_FOLDER: ''
SFTP_HOST: ''
SFTP_USER: ''
SFTP_PASSWORD: ''

RACK_MULTIPART_PART_LIMIT: "0"
RACK_MULTIPART_LIMIT: "0"

RECAPTCHA_SITE_KEY: ""
RECAPTCHA_SECRET_KEY: ""
