# Configuration all env mail
SMTP_ADDRESS: "smtp.emailemnuvem.com.br"
SMTP_PORT: "587"
SMTP_DOMAIN: "agenciaw3.digital"
SMTP_USER_NAME: "no-replay@agenciaw3.digital"
SMTP_PASSWORD: ""

# From email
SMTP_FROM_MAIL: "atendimento@agenciaw3.digital"

# Paths and URls
UPLOAD_HOST: "http://cdn1.localtest.me:3000/"
SFTP_FOLDER: ""
SFTP_HOST: ""
SFTP_USER: ""
SFTP_PASSWORD: ""

RACK_MULTIPART_PART_LIMIT: "0"
RACK_MULTIPART_LIMIT: "0"

RECAPTCHA_SITE_KEY: ""
RECAPTCHA_SECRET_KEY: ""

DOMAIN: "http://localhost:3000"
